In [2]:
import torch

In [3]:
x=torch.empty(3)
print(x)

tensor([6.9292e+29, 3.1753e-41, 0.0000e+00])


In [4]:
x=torch.empty(3,3,3)
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -2.3754e-02],
         [ 4.4755e-41, -2.3754e-02,  4.4755e-41]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [5]:
t3=torch.tensor([[5,6],[7,8],[9,10]])
print(t3)

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [25]:
# 3-d
t3=torch.tensor([[[1,2,3],[3,4,5],[5,6,7],[3,4,5]]])
print(t3)

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7],
         [3, 4, 5]]])


In [27]:
t3=torch.tensor([[[1,2,3],[2,3,4]],[[1,2,3],[4,5,6]]])
print(t3)
print(t3.shape)

tensor([[[1, 2, 3],
         [2, 3, 4]],

        [[1, 2, 3],
         [4, 5, 6]]])
torch.Size([2, 2, 3])


In [26]:
print(t3.shape)

torch.Size([1, 4, 3])


In [6]:
#Tensor with random values
x=torch.rand(2,2)
print(x)

tensor([[0.1914, 0.2182],
        [0.3724, 0.5528]])


In [7]:
x=torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [8]:
x=torch.ones(2,2,dtype=torch.int)  # torch.double, torch.float16
print(x)
print(x.dtype)
print(x.size())

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32
torch.Size([2, 2])


In [9]:
# Tensor with list
x=torch.tensor([2.3,1.2,4.5,6.6])
print(x)

tensor([2.3000, 1.2000, 4.5000, 6.6000])


In [10]:
# Basic operations
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=x+y
print(z)
z=torch.add(x,y)
print(z)
y.add_(x)
print(y)

tensor([[0.6606, 0.1373],
        [0.3689, 0.2338]])
tensor([[0.0604, 0.6427],
        [0.2936, 0.5061]])
tensor([[0.7210, 0.7800],
        [0.6625, 0.7399]])
tensor([[0.7210, 0.7800],
        [0.6625, 0.7399]])
tensor([[0.7210, 0.7800],
        [0.6625, 0.7399]])


In [11]:
# Subtracting
z=x-y
print(z)
z=torch.sub(x,y)
print(z)
y.sub_(x)
print(y)


tensor([[-0.0604, -0.6427],
        [-0.2936, -0.5061]])
tensor([[-0.0604, -0.6427],
        [-0.2936, -0.5061]])
tensor([[0.0604, 0.6427],
        [0.2936, 0.5061]])


In [12]:
# Multiply
z=x*y
print(z)
z=torch.mul(x,y)
print(z)
y.mul_(x)
print(y)

tensor([[0.0399, 0.0882],
        [0.1083, 0.1183]])
tensor([[0.0399, 0.0882],
        [0.1083, 0.1183]])
tensor([[0.0399, 0.0882],
        [0.1083, 0.1183]])


In [13]:
#Division
z=x/y
print(z)
z=torch.div(x,y)
print(z)
y.div_(x)
print(y)

tensor([[16.5609,  1.5559],
        [ 3.4061,  1.9758]])
tensor([[16.5609,  1.5559],
        [ 3.4061,  1.9758]])
tensor([[0.0604, 0.6427],
        [0.2936, 0.5061]])


In [14]:
#Slicing
x=torch.rand(5,3)
print(x)
# all rows column 0
print(x[:,0])
# rows no 1 and all column
print(x[1,:])
print(x[0:2,0:2])
print(x[0,0])
print(x[1,1].item())

tensor([[0.3430, 0.9419, 0.2311],
        [0.7703, 0.9031, 0.5896],
        [0.2503, 0.3788, 0.5870],
        [0.5821, 0.9543, 0.1631],
        [0.3853, 0.3112, 0.8249]])
tensor([0.3430, 0.7703, 0.2503, 0.5821, 0.3853])
tensor([0.7703, 0.9031, 0.5896])
tensor([[0.3430, 0.9419],
        [0.7703, 0.9031]])
tensor(0.3430)
0.9031434059143066


In [15]:
# Reshaping Tensor
x=torch.rand(4,4)
print(x)
y=x.view(2,8)
print(y)
print(y.size())

tensor([[0.1374, 0.2674, 0.7974, 0.7574],
        [0.3736, 0.1684, 0.3922, 0.3878],
        [0.1342, 0.0993, 0.8807, 0.6373],
        [0.7875, 0.0814, 0.9549, 0.4662]])
tensor([[0.1374, 0.2674, 0.7974, 0.7574, 0.3736, 0.1684, 0.3922, 0.3878],
        [0.1342, 0.0993, 0.8807, 0.6373, 0.7875, 0.0814, 0.9549, 0.4662]])
torch.Size([2, 8])


In [16]:
# Numpy to torch tensor and vise versa
import numpy as np

In [17]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b=a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [19]:
# in cpu both a and b share the same memory
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
# Numpy to Tensor
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [21]:
b=torch.from_numpy(a)
print(b)
print(type(b))
a+=1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
  device=torch.device("cuda")
  x=torch.ones(5,device=device)
  y=torch.ones(5)
  y=y.to(device)
  z=x+y
  z=z.to("cpu")
  print(z)
else: print("no cuda")

no cuda
