## Tensor Operations and Gradients
### We can combine tensors with the usual arithmetic operations.

In [7]:
import torch
# create tensors
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
print(x,w,b)

tensor(3.) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [8]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [9]:
# compute derivatives
y.backward()

### The derivatives of y with respect to the input tensor are stored in the .grad property of the respective tensor

In [10]:
# Display Gradients
print("dy/dx: ",x.grad)
print("dy/dw: ",w.grad)
print("dy/db: ",b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [12]:
# Create a tensor with a fixed value for every element
t1=torch.full((3,2),42)
t1

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [13]:
t2=torch.full((3,2),42)
t2

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [15]:
# concatenate two tensor with compatible shapes
t3=torch.cat((t1,t2))
print(t3)

tensor([[42, 42],
        [42, 42],
        [42, 42],
        [42, 42],
        [42, 42],
        [42, 42]])


In [16]:
t4=torch.sin(t3)
t4

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [17]:
t4.shape

torch.Size([6, 2])

In [18]:
#Reshape
t5=t4.reshape(3,2,2)
t5

tensor([[[-0.9165, -0.9165],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

## Interoperability with Numpy

In [19]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [20]:
# convert numpy array to a torch tensor
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [21]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [22]:
# convert a torch tensor to a numpy array
z=y.numpy()
z

array([[1, 2],
       [3, 4]])

In [32]:
x=torch.tensor([2.,3.,4.],requires_grad=True)
print(x)

tensor([2., 3., 4.], requires_grad=True)


In [33]:
y=x+2
print(y)

tensor([4., 5., 6.], grad_fn=<AddBackward0>)


In [34]:
z=y*y*2
z

tensor([32., 50., 72.], grad_fn=<MulBackward0>)

In [39]:
v=torch.tensor([1,1,1],dtype=torch.float32)
z.backward(v)
print(x.grad) # dz/dx

tensor([16., 20., 24.])


## Preventing Gradient History

In [40]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 2.2276, -0.0932, -0.2430], requires_grad=True)


In [41]:
x.requires_grad_(False)
x

tensor([ 2.2276, -0.0932, -0.2430])

In [42]:
y=x.detach()
print(y)

tensor([ 2.2276, -0.0932, -0.2430])


In [56]:
# Training Example
weights=torch.ones(4,requires_grad=True)
print(weights)

#model=(weights*3).sum()
#print(model)
v=torch.tensor([1,1,1,1],dtype=torch.float32)
for epoch in range(4):
    model=(weights*3)
    model.backward(v)
    print(weights.grad)
    weights.grad.zero_()


tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
