In [2]:
import torch
import numpy as np

## Training Data

In [4]:
# input (temp,rainfall,humidity)
inputs=np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
],dtype='float32')

In [5]:
# Targets (apples,oranges)
targets=np.array([
    [56,70],
    [81,101],
    [119,133],
    [22,37],
    [103,119]
],dtype='float32')

In [6]:
#Convert inputs and targets to tensor
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear Regression Model From Scratch
- yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
- yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2

In [7]:
# Weight and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)


tensor([[ 0.2272, -0.5664,  0.1675],
        [-0.1789, -0.1178,  0.5309]], requires_grad=True)
tensor([0.3073, 0.0758], requires_grad=True)


In [9]:
def model(x):
    return x @ w.t()+b

## Loss function

In [10]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

# Compute Gradients

In [11]:
preds=model(inputs)
print(preds)

tensor([[-13.8522,   1.9505],
        [-18.1393,   7.4044],
        [-46.1089,  -0.4847],
        [  5.3270,  -3.5947],
        [-26.6650,  13.5824]], grad_fn=<AddBackward0>)


In [12]:
loss=mse(preds,targets)
print(loss)

tensor(10302.9736, grad_fn=<DivBackward0>)


In [13]:
loss.backward()

In [14]:
print(w)
print(w.grad)

tensor([[ 0.2272, -0.5664,  0.1675],
        [-0.1789, -0.1178,  0.5309]], requires_grad=True)
tensor([[-7826.5796, -9738.7480, -5723.6665],
        [-7302.4912, -8509.6680, -5107.9189]])


In [15]:
# adjust w and b
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [17]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(7200.0952, grad_fn=<DivBackward0>)


## Training for multiple epochs

In [22]:
# Training for 100 epochs
for i in range(1000):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [23]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(0.5201, grad_fn=<DivBackward0>)
