## Linear regression using PyTorch built-ins

We've implemented linear regression & gradient descent model using some basic tensor operations. However, since this is a common pattern in deep learning, PyTorch provides several built-in functions and classes to make it easy to create and train models with just a few lines of code.

Let's begin by importing the torch.nn package from PyTorch, which contains utility classes for building neural networks.



In [5]:
import torch
import torch.nn as nn
import numpy as np

In [8]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

In [9]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [13]:
from torch.utils.data import TensorDataset

In [22]:
# Define dataset
train_ds=TensorDataset(inputs,targets)
train_ds[0:,]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 74.,  66.,  43.],
         [ 91.,  87.,  65.],
         [ 88., 134.,  59.],
         [101.,  44.,  37.],
         [ 68.,  96.,  71.],
         [ 73.,  66.,  44.],
         [ 92.,  87.,  64.],
         [ 87., 135.,  57.],
         [103.,  43.,  36.],
         [ 68.,  97.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [24]:
from torch.utils.data import DataLoader

In [26]:
# Define data loader
batch_size=5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [27]:
for xb,yb in train_dl:
  print(xb)
  print(yb)

tensor([[ 87., 135.,  57.],
        [ 68.,  96.,  71.],
        [ 74.,  66.,  43.],
        [ 87., 134.,  58.],
        [ 91.,  87.,  65.]])
tensor([[118., 134.],
        [104., 118.],
        [ 57.,  69.],
        [119., 133.],
        [ 80., 102.]])
tensor([[ 88., 134.,  59.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[118., 132.],
        [ 81., 101.],
        [103., 119.],
        [ 22.,  37.],
        [ 56.,  70.]])
tensor([[103.,  43.,  36.],
        [101.,  44.,  37.],
        [ 92.,  87.,  64.],
        [ 68.,  97.,  70.],
        [ 73.,  66.,  44.]])
tensor([[ 20.,  38.],
        [ 21.,  38.],
        [ 82., 100.],
        [102., 120.],
        [ 57.,  69.]])


## nn.Linear

In [28]:
# Define Model
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2305, -0.0855,  0.3380],
        [ 0.1087,  0.4144,  0.3595]], requires_grad=True)
Parameter containing:
tensor([ 0.3050, -0.1375], requires_grad=True)


PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [29]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2305, -0.0855,  0.3380],
         [ 0.1087,  0.4144,  0.3595]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3050, -0.1375], requires_grad=True)]

In [30]:
# Generate Predictions
preds=model(inputs)
preds

tensor([[-7.7160e+00,  5.1018e+01],
        [-6.5621e+00,  6.9225e+01],
        [-1.1602e+01,  8.5695e+01],
        [-1.4377e+01,  4.2068e+01],
        [-1.4661e-01,  7.2306e+01],
        [-7.8610e+00,  5.0712e+01],
        [-6.1385e+00,  6.9170e+01],
        [-1.1494e+01,  8.6163e+01],
        [-1.4232e+01,  4.2374e+01],
        [ 4.2195e-01,  7.2556e+01],
        [-7.2924e+00,  5.0963e+01],
        [-6.7071e+00,  6.8920e+01],
        [-1.2026e+01,  8.5750e+01],
        [-1.4945e+01,  4.1818e+01],
        [-1.6125e-03,  7.2611e+01]], grad_fn=<AddmmBackward0>)

## Loss Function

In [32]:
## import nn.functional
import torch.nn.functional as F

The `nn.functional` package contains many useful loss functions and several other utilities.

In [33]:
# Define loss function
loss_fn=F.mse_loss

In [35]:
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(4631.2373, grad_fn=<MseLossBackward0>)


## Optimizer

In [37]:
# Define optimiser
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

## Train Model

In [38]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
  # repeat for given number of epochs
  for epoch in range(num_epochs):
    # Train with batches of data
    for xb,yb in train_dl:
      # Generate predictions
      pred=model(xb)
      # calculate loss
      loss=loss_fn(pred,yb)
      # compute gradients
      loss.backward()
      # update parameters using gradients
      opt.step()
      #Reset gradients with zeros
      opt.zero_grad()
    # Print the progress
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [40]:
fit(200,model,loss_fn,opt,train_dl)

Epoch [10/200], Loss: 11.1143
Epoch [20/200], Loss: 11.2359
Epoch [30/200], Loss: 6.8847
Epoch [40/200], Loss: 7.1307
Epoch [50/200], Loss: 6.6479
Epoch [60/200], Loss: 5.9534
Epoch [70/200], Loss: 2.1430
Epoch [80/200], Loss: 3.3117
Epoch [90/200], Loss: 5.4270
Epoch [100/200], Loss: 6.3207
Epoch [110/200], Loss: 3.2807
Epoch [120/200], Loss: 3.9587
Epoch [130/200], Loss: 1.8497
Epoch [140/200], Loss: 3.8043
Epoch [150/200], Loss: 4.5567
Epoch [160/200], Loss: 4.0939
Epoch [170/200], Loss: 5.8418
Epoch [180/200], Loss: 3.0931
Epoch [190/200], Loss: 3.4242
Epoch [200/200], Loss: 1.7054


In [41]:
preds=model(inputs)
preds

tensor([[ 57.0663,  70.4914],
        [ 81.9896,  99.3361],
        [118.3406, 135.1959],
        [ 20.9937,  38.4624],
        [101.7267, 115.9817],
        [ 55.8189,  69.3912],
        [ 81.8318,  99.2141],
        [118.6251, 135.6807],
        [ 22.2411,  39.5626],
        [102.8163, 116.9599],
        [ 56.9084,  70.3694],
        [ 80.7422,  98.2358],
        [118.4985, 135.3179],
        [ 19.9041,  37.4841],
        [102.9741, 117.0819]], grad_fn=<AddmmBackward0>)

In [42]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])